---
abstract: 'A POE Component implementation of NRPE Daemon.'
author:
  - 'Chris Williams <chris@bingosnet.co.uk>'
build_requires:
  Test::More: 0.47
distribution_type: module
generated_by: 'Module::Install version 0.79'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: POE-Component-Server-NRPE
no_index:
  directory:
    - examples
    - inc
    - t
requires:
  Carp: 0
  Net::Netmask: 1.9015
  Net::SSLeay: 1.3
  POE: 0.38
  POE::Component::Client::NRPE: 0.12
  POE::Component::SSLify: 0.15
  Socket: 0
  perl: 5.6.0
resources:
  license: http://dev.perl.org/licenses/
version: 0.10
