---
abstract: 'A POE Component implementation of NRPE Daemon.'
author:
  - 'Chris Williams <chris@bingosnet.co.uk>'
  - 'Rocco Caputo <rcaputo@cpan.org>'
  - 'Olivier Raginel <github@babar.us>'
build_requires:
  Test::More: 0.47
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300028, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: POE-Component-Server-NRPE
requires:
  Carp: 0
  Net::Netmask: 1.9015
  Net::SSLeay: 1.3
  POE: 1.004
  POE::Component::Client::NRPE: 0.12
  POE::Component::SSLify: 0.15
  Socket: 0
  perl: 5.006
resources:
  homepage: https://github.com/bingos/poe-component-server-nrpe
  repository: https://github.com/bingos/poe-component-server-nrpe.git
version: 0.18
